function updateUnit(u,dt){const d=DEF[u.key];if(u.dead){u.deathT-=dt;u.anim+=dt*5;return}u.hitT=Math.max(0,u.hitT-dt);u.spawnT=Math.max(0,u.spawnT-dt);u.recoil*=Math.max(0,1-dt*9);u.attackT=Math.max(0,u.attackT-dt);u.buffT=Math.max(0,u.buffT-dt);u.anim+=dt*(u.state==='attack'?10:5.5);const[en,dist]=nearest(u),dir=u.team==='player'?1:-1;let move=d.speed*(u.buffT>0?1.18:1);if(d.kind==='cavalry'||d.kind==='boss'){u.chargeT+=dt;if(u.state==='walk'&&Math.random()<dt*5)st.particles.push({x:u.x-u.dir*35,y:u.y-2,vx:-u.dir*(18+Math.random()*20),vy:-10-Math.random()*24,life:.3+Math.random()*.25,size:4+Math.random()*6,color:'rgba(188,156,118,.65)'})}else u.chargeT=0;
  if(u.team==='player'){if(st.order==='hold')move=Math.min(move,20);if(st.order==='retreat')move=-Math.abs(move*.85);if(st.order==='assault')move*=1.07}
  const effectiveRange=d.range+(d.kind==='ranged'?12:0);
  if(en&&dist<=effectiveRange){u.state='attack';u.chargeT=0;if(u.attackT<=0){u.attackT=d.rate;u.anim=4.05;u.shotReady=true;if(d.kind==='ranged')launchArrow(u,en);else meleeAttack(u,en)}}
  else{u.state='walk';u.x+=dir*move*dt+spacing(u)*dt;if(u.team==='player'&&st.order==='retreat'&&u.x<LEFT_BASE_X+38)u.x=LEFT_BASE_X+38;if(u.team==='player'&&u.x>RIGHT_BASE_X-20)attackBase(u,'right');if(u.team==='enemy'&&u.x<LEFT_BASE_X+20)attackBase(u,'left')}
}
function attackBase(u,side){const d=DEF[u.key];u.state='attack';if(u.attackT<=0){u.attackT=d.rate*1.05;let amount=d.dmg*(d.kind==='boss'?1.5:1);if(side==='right')st.rightHp-=amount;else st.leftHp-=amount;st.shake=Math.max(st.shake,d.kind==='boss'?8:3);burst(u.x,u.y-70,8,'#ffb36b')}}
function updateProjectiles(dt){for(let i=st.projectiles.length-1;i>=0;i--){const p=st.projectiles[i],target=st.units.find(u=>u.id===p.target&&!u.dead);if(target){p.tx=target.x;p.ty=target.y-92}const dx=p.tx-p.x,dy=p.ty-p.y,dist=Math.hypot(dx,dy);const step=p.speed*dt;if(dist<=step+8){if(target)damage({team:p.team,key:p.team==='player'?'archer':'enemyArcher'},target,p.dmg,false);burst(p.tx,p.ty,6,p.team==='player'?'#d9f1ff':'#ffd2cf');st.projectiles.splice(i,1);continue}p.x+=dx/dist*step;p.y+=dy/dist*step;p.t+=dt}}
function updateMeteors(dt){for(let i=st.meteors.length-1;i>=0;i--){const m=st.meteors[i];m.delay-=dt;if(m.delay>0)continue;m.y+=880*dt;m.x+=120*dt;if(m.y>=m.ty){alive('enemy').forEach(e=>{if(Math.abs(e.x-m.tx)<115&&Math.abs(e.y-m.ty)<100)damage({team:'player',key:'arthos',buffT:0},e,90,true)});burst(m.tx,m.ty,36,'#ffb15f');st.shake=Math.max(st.shake,10);st.meteors.splice(i,1)}}}
function updateFx(dt){for(let i=st.particles.length-1;i>=0;i--){const p=st.particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=250*dt;p.life-=dt;if(p.life<=0)st.particles.splice(i,1)}for(let i=st.numbers.length-1;i>=0;i--){const n=st.numbers[i];n.t+=dt;n.y-=38*dt;n.life-=dt;if(n.life<=0)st.numbers.splice(i,1)}st.embers.forEach(e=>{e.x+=e.vx*dt;e.y+=e.vy*dt;if(e.y<300||e.x<0||e.x>W){e.x=Math.random()*W;e.y=H-50+Math.random()*40}});st.smoke.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(s.life<0){s.life=1;s.x=s.baseX+(Math.random()*40-20);s.y=s.baseY}})}

function update(dt){if(st.paused||st.finished)return;dt*=st.speed;st.time+=dt;st.mana=Math.min(st.maxMana,st.mana+29*dt);st.heroCd=Math.max(0,st.heroCd-dt);st.meteorCd=Math.max(0,st.meteorCd-dt);st.rallyCd=Math.max(0,st.rallyCd-dt);st.healCd=Math.max(0,st.healCd-dt);st.rallyT=Math.max(0,st.rallyT-dt);st.healGlow=Math.max(0,st.healGlow-dt);if(st.comboT>0){st.comboT-=dt;if(st.comboT<=0)st.combo=0}Object.keys(st.cool).forEach(k=>st.cool[k]=Math.max(0,st.cool[k]-dt));
  if(st.queue.length){st.spawnT-=dt;if(st.spawnT<=0){const k=st.queue.shift();spawnEnemy(k);st.spawnT=.72+Math.random()*.32}}
  else if(!alive('enemy').length){if(st.wave<WAVES.length-1){st.nextWaveT=(st.nextWaveT||3.3)-dt;if(st.nextWaveT<=0)setWave(st.wave+1)}else if(st.rightHp>0)finish(true)}
  if(st.rallyT>0)alive('player').forEach(u=>u.buffT=Math.max(u.buffT,.2));
  st.units.forEach(u=>updateUnit(u,dt));updateProjectiles(dt);updateMeteors(dt);updateFx(dt);for(let i=st.groundFx.length-1;i>=0;i--){st.groundFx[i].life-=dt;if(st.groundFx[i].life<=0)st.groundFx.splice(i,1)}st.units=st.units.filter(u=>!u.dead||u.deathT>0);
  if(st.leftHp<=0)finish(false);if(st.rightHp<=0)finish(true);
}

function frameFor(u){if(u.dead){return 8+Math.min(3,Math.max(0,Math.floor((1-u.deathT/1.35)*4)))}if(u.state==='attack'){return 4+(Math.floor(u.anim)%4)}return Math.floor(u.anim)%4}
function drawSheet(u){const d=DEF[u.key],img=u.team==='player'?IMG.friend:IMG.enemy,off=OFF[u.key],frame=frameFor(u),sx=off[0]+(frame%4)*CELL,sy=off[1]+Math.floor(frame/4)*CELL;let dw=d.w,dh=d.h;if(u.lane===0){dw*=.94;dh*=.94}else if(u.lane===2){dw*=1.04;dh*=1.04}const x=u.x+u.recoil,y=u.y;ctx.save();if(u.team==='enemy'){ctx.translate(x,y);ctx.scale(-1,1);ctx.translate(-x,-y)}ctx.globalAlpha=u.dead?Math.max(.35,u.deathT/1.35):Math.min(1,1-u.spawnT*2.8);ctx.fillStyle='rgba(0,0,0,.34)';ctx.beginPath();ctx.ellipse(x,y+2,dw*.27,dh*.065,0,0,Math.PI*2);ctx.fill();if(u.key==='arthos'){const g=ctx.createRadialGradient(x,y-dh*.5,15,x,y-dh*.5,90);g.addColorStop(0,'rgba(91,188,255,.26)');g.addColorStop(1,'rgba(91,188,255,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y-dh*.5,90,0,Math.PI*2);ctx.fill()}if(u.hitT>0)ctx.filter='brightness(1.5) saturate(1.25)';ctx.drawImage(img,sx,sy,CELL,CELL,x-dw/2,y-dh,dw,dh);ctx.restore();if(!u.dead){const bw=d.kind==='boss'?96:Math.max(34,dw*.44),yy=y-dh-4;ctx.fillStyle='#050607cc';ctx.fillRect(x-bw/2-1,yy-1,bw+2,7);ctx.fillStyle='#272d35';ctx.fillRect(x-bw/2,yy,bw,5);ctx.fillStyle=u.team==='player'?'#4bb9ff':'#ff6068';ctx.fillRect(x-bw/2,yy,bw*Math.max(0,u.hp/u.maxHp),5);if(d.kind==='boss'){ctx.font='900 9px Arial';ctx.fillStyle='#ffd3d3';ctx.textAlign='center';ctx.fillText('WARMASTER',x,yy-5)}}}
function drawProjectiles(){for(const p of st.projectiles){ctx.save();const ang=Math.atan2(p.ty-p.y,p.tx-p.x);ctx.translate(p.x,p.y);ctx.rotate(ang);ctx.strokeStyle=p.team==='player'?'#dcefff':'#ffb7b3';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-14,0);ctx.lineTo(14,0);ctx.stroke();ctx.fillStyle=p.team==='player'?'#dcefff':'#ffb7b3';ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(8,-4);ctx.lineTo(8,4);ctx.closePath();ctx.fill();ctx.restore()}for(const m of st.meteors){if(m.delay>0)continue;const g=ctx.createRadialGradient(m.x,m.y,3,m.x,m.y,28);g.addColorStop(0,'#fff3bf');g.addColorStop(.35,'#ffad4e');g.addColorStop(1,'rgba(255,70,20,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(m.x,m.y,28,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ff8a3d';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(m.x-80,m.y-90);ctx.lineTo(m.x,m.y);ctx.stroke()}}
function drawAtmos(){ctx.save();for(const e of st.embers){ctx.globalAlpha=e.a;ctx.fillStyle='#ffb05d';ctx.fillRect(e.x,e.y,e.s,e.s)}ctx.globalAlpha=1;for(const s of st.smoke){const g=ctx.createRadialGradient(s.x,s.y,3,s.x,s.y,s.r);g.addColorStop(0,'rgba(33,29,31,.18)');g.addColorStop(1,'rgba(15,14,16,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawNumbers(){ctx.save();ctx.textAlign='center';for(const n of st.numbers){ctx.globalAlpha=Math.max(0,n.life/.75);ctx.font=`900 ${n.crit?20:15}px Arial`;ctx.lineWidth=3;ctx.strokeStyle='#000';ctx.strokeText(n.text,n.x,n.y);ctx.fillStyle=n.crit?'#ffd36b':n.color;ctx.fillText(n.text,n.x,n.y)}ctx.restore();ctx.globalAlpha=1}
function render(){ctx.save();if(st.shake>0){const s=st.shake;ctx.translate((Math.random()*2-1)*s,(Math.random()*2-1)*s);st.shake*=.86}ctx.drawImage(IMG.bg,0,0,W,H);const side=ctx.createLinearGradient(0,0,W,0);side.addColorStop(0,'rgba(17,83,148,.12)');side.addColorStop(.42,'rgba(0,0,0,0)');side.addColorStop(.58,'rgba(0,0,0,0)');side.addColorStop(1,'rgba(157,28,31,.14)');ctx.fillStyle=side;ctx.fillRect(0,0,W,H);const dusk=ctx.createLinearGradient(0,0,0,H);dusk.addColorStop(0,'rgba(4,7,11,.05)');dusk.addColorStop(.58,'rgba(5,5,5,.02)');dusk.addColorStop(1,'rgba(2,3,4,.22)');ctx.fillStyle=dusk;ctx.fillRect(0,0,W,H);for(const g of st.groundFx){ctx.globalAlpha=Math.min(.22,g.life/4*.22);ctx.fillStyle=g.team==='enemy'?'#240607':'#081624';ctx.beginPath();ctx.ellipse(g.x,g.y,g.size,g.size*.24,0,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;drawAtmos();const units=[...st.units].sort((a,b)=>a.y-b.y||a.x-b.x);units.forEach(drawSheet);drawProjectiles();for(const p of st.particles){ctx.globalAlpha=Math.max(0,p.life/.67);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;if(st.leftHp<st.maxHp*.45){const g=ctx.createRadialGradient(160,545,8,160,545,150);g.addColorStop(0,'rgba(54,97,135,.18)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,360,330,330)}if(st.rightHp<st.maxHp*.45){const g=ctx.createRadialGradient(W-150,525,8,W-150,525,170);g.addColorStop(0,'rgba(180,48,39,.2)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(W-340,330,340,350)}drawNumbers();ctx.restore()}
