function castHero(){if(st.heroCd>0)return toast('Arthos is regrouping');if(st.mana<140)return toast('Need 140 mana');if(alive('player').some(u=>u.key==='arthos'))return toast('Arthos is already fighting');st.mana-=140;st.heroCd=28;const u=makeUnit('arthos','player',LEFT_BASE_X+30,1);st.units.push(u);banner('ARTHOS ENTERS THE FIELD');log('Arthos, Ashen Blade of Ravenhold, joins the battle.');st.shake=4}
function castMeteor(){if(st.meteorCd>0)return toast('Meteor Rain is recharging');if(st.mana<180)return toast('Need 180 mana');st.mana-=180;st.meteorCd=16;const enemies=alive('enemy');const center=enemies.length?enemies.reduce((a,u)=>a+u.x,0)/enemies.length:1120;for(let i=0;i<11;i++)st.meteors.push({x:center-300+Math.random()*520,y:-160-Math.random()*100,tx:center-180+Math.random()*360,ty:620+Math.random()*160,delay:i*.1});banner('METEOR RAIN');log('The sky burns over the Obsidian line.')}
function castRally(){if(st.rallyCd>0)return toast('War Cry is recharging');if(st.mana<100)return toast('Need 100 mana');st.mana-=100;st.rallyCd=14;st.rallyT=7;alive('player').forEach(u=>u.buffT=7);banner('WAR CRY');log('Ravenhold surges forward with +22% damage and speed.')}
function castHeal(){if(st.healCd>0)return toast('Holy Light is recharging');if(st.mana<120)return toast('Need 120 mana');st.mana-=120;st.healCd=13;alive('player').forEach(u=>{u.hp=Math.min(u.maxHp,u.hp+Math.max(85,u.maxHp*.28));burst(u.x,u.y-90,10,'#b7ffd0')});st.leftHp=Math.min(st.maxHp,st.leftHp+260);st.healGlow=1;banner('HOLY LIGHT');log('Ravenhold troops are restored.')}
function setOrder(o){st.order=o;$$('.order').forEach(b=>b.classList.toggle('active',b.dataset.order===o));UI.status.textContent=o.toUpperCase();UI.order.textContent=o.toUpperCase();log(`Order changed: ${o.toUpperCase()}.`)}
function finish(win){if(st.finished)return;st.finished=true;st.paused=true;UI.end.classList.remove('hidden');UI.endTitle.textContent=win?'VICTORY':'RAVENHOLD FALLS';UI.endText.textContent=win?`The Obsidian line is broken. ${st.kills} enemies defeated and ${st.gold} gold recovered.`:`The Obsidian Legion breached Ravenhold after ${st.kills} confirmed kills.`}
function reset(){Object.assign(st,{units:[],projectiles:[],particles:[],numbers:[],meteors:[],groundFx:[],mana:300,gold:0,kills:0,combo:0,comboT:0,wave:0,queue:[],spawnT:1,nextWaveT:0,leftHp:5000,rightHp:5000,time:0,paused:false,order:'assault',shake:0,heroCd:0,meteorCd:0,rallyCd:0,healCd:0,rallyT:0,finished:false,cool:{sword:0,spear:0,archer:0,cavalry:0},logs:[]});UI.end.classList.add('hidden');setOrder('assault');setWave(0);spawnPlayer('sword',true,1);spawnPlayer('archer',true,0);log('Ravenhold forward line established.')}

function updateUI(){UI.leftHpBar.style.width=`${Math.max(0,st.leftHp/st.maxHp*100)}%`;UI.rightHpBar.style.width=`${Math.max(0,st.rightHp/st.maxHp*100)}%`;UI.leftHpText.textContent=`${Math.max(0,Math.ceil(st.leftHp))} / ${st.maxHp}`;UI.rightHpText.textContent=`${Math.max(0,Math.ceil(st.rightHp))} / ${st.maxHp}`;UI.mana.textContent=Math.floor(st.mana);UI.gold.textContent=st.gold;UI.kills.textContent=st.kills;UI.combo.textContent=st.combo;UI.wave.textContent=`WAVE ${st.wave+1} / ${WAVES.length}`;UI.army.textContent=`${alive('player').length} vs ${alive('enemy').length}`;UI.next.textContent=st.queue.length?`${st.queue.length} incoming`:st.wave<WAVES.length-1?(st.nextWaveT>0?`${st.nextWaveT.toFixed(1)}s`:'clearing'):'FINAL';UI.hero.textContent=st.heroCd>0?`${st.heroCd.toFixed(1)}s`:'READY';UI.hero.className=st.heroCd>0?'warn':'ready';
  const p=alive('player'),e=alive('enemy'),pf=p.length?Math.max(...p.map(u=>u.x)):LEFT_BASE_X,ef=e.length?Math.min(...e.map(u=>u.x)):RIGHT_BASE_X;const m=((pf+ef)/2-LEFT_BASE_X)/(RIGHT_BASE_X-LEFT_BASE_X);UI.frontMarker.style.left=`${Math.max(0,Math.min(100,m*100))}%`;UI.frontBlue.style.width=`${Math.max(2,Math.min(48,(pf-LEFT_BASE_X)/(RIGHT_BASE_X-LEFT_BASE_X)*50))}%`;UI.frontRed.style.width=`${Math.max(2,Math.min(48,(RIGHT_BASE_X-ef)/(RIGHT_BASE_X-LEFT_BASE_X)*50))}%`;
  $$('.unitCard').forEach(c=>{const k=c.dataset.unit,d=DEF[k],cd=st.cool[k]||0,disabled=st.mana<d.cost||cd>0||st.finished;c.classList.toggle('disabled',disabled);c.querySelector('.cooldown').style.height=`${cd>0?Math.min(100,cd/(d.cool||1)*100):0}%`});
  const abil=[['#heroBtn',st.heroCd,28,140],['#meteorBtn',st.meteorCd,16,180],['#rallyBtn',st.rallyCd,14,100],['#healBtn',st.healCd,13,120]];abil.forEach(([sel,cd,max,cost])=>{const b=$(sel);b.classList.toggle('disabled',cd>0||st.mana<cost||st.finished);b.querySelector('i').style.height=`${cd>0?cd/max*100:0}%`})}
function drawCards(){const atlasFor={sword:IMG.friend,spear:IMG.friend,archer:IMG.friend,cavalry:IMG.friend};$$('.unitCard').forEach(c=>{const cv=c.querySelector('canvas'),cc=cv.getContext('2d'),k=c.dataset.unit,off=OFF[k];cc.clearRect(0,0,cv.width,cv.height);const img=atlasFor[k],scale=k==='cavalry'?1.05:.88,sz=118*scale;cc.drawImage(img,off[0],off[1],CELL,CELL,(cv.width-sz)/2,cv.height-sz+9,sz,sz)})}
function bind(){$$('.unitCard').forEach(c=>c.onclick=()=>spawnPlayer(c.dataset.unit));$$('.speed').forEach(b=>b.onclick=()=>{st.speed=+b.dataset.speed;$$('.speed').forEach(x=>x.classList.toggle('active',x===b))});$('#pauseBtn').onclick=()=>{st.paused=!st.paused;toast(st.paused?'Paused':'Battle resumed')};$$('.order').forEach(b=>b.onclick=()=>setOrder(b.dataset.order));$('#heroBtn').onclick=castHero;$('#meteorBtn').onclick=castMeteor;$('#rallyBtn').onclick=castRally;$('#healBtn').onclick=castHeal;$('#restartBtn').onclick=reset;addEventListener('keydown',ev=>{const k=ev.key.toLowerCase();if(k==='1')spawnPlayer('sword');if(k==='2')spawnPlayer('spear');if(k==='3')spawnPlayer('archer');if(k==='4')spawnPlayer('cavalry');if(k==='q')castHero();if(k==='w')castMeteor();if(k==='e')castRally();if(k==='r')castHeal();if(k==='a')setOrder('assault');if(k==='s')setOrder('hold');if(k==='d')setOrder('retreat');if(ev.code==='Space'){ev.preventDefault();st.paused=!st.paused}})}
function initFx(){st.embers=Array.from({length:85},()=>({x:Math.random()*W,y:350+Math.random()*H*.6,vx:-6+Math.random()*12,vy:-12-Math.random()*26,s:1+Math.random()*2.5,a:.18+Math.random()*.46}));st.smoke=[{baseX:420,baseY:370},{baseX:760,baseY:330},{baseX:1030,baseY:320},{baseX:1300,baseY:350}].flatMap(p=>Array.from({length:5},()=>({x:p.baseX+Math.random()*30,y:p.baseY+Math.random()*30,baseX:p.baseX,baseY:p.baseY,vx:-5+Math.random()*10,vy:-4-Math.random()*8,r:40+Math.random()*80,life:Math.random()})))}
let last=0;function loop(ts){const dt=Math.min(.033,(ts-last)/1000||.016);last=ts;update(dt);render();updateUI();requestAnimationFrame(loop)}
async function loadChunkAsset(prefix,count){let b64='';for(let i=0;i<count;i++){const r=await fetch(`assets/major/${prefix}_${String(i).padStart(2,'0')}.txt?v=major10`,{cache:'no-store'});if(!r.ok)throw new Error(`${prefix} chunk ${i}: ${r.status}`);b64+=(await r.text()).trim()}return load(`data:image/avif;base64,${b64}`)}
Promise.all([
 loadChunkAsset('bg',13).then(i=>IMG.bg=i),
 loadChunkAsset('friend',10).then(i=>IMG.friend=i),
 loadChunkAsset('enemy',10).then(i=>IMG.enemy=i)
]).then(()=>{initFx();bind();drawCards();reset();requestAnimationFrame(loop)}).catch(err=>{document.body.innerHTML=`<div style="padding:24px;color:white;font-family:Arial;background:#080b0f;height:100vh">Warfront failed to load: ${err.message}</div>`;console.error(err)});
